# Generated by Django 4.2.1 on 2023-05-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('old', 'Старая')], default='new', max_length=10),
        ),
    ]
