# Generated by Django 4.2.1 on 2023-05-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0002_categories_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
